"""initial

Revision ID: bbf4eaa6b09b
Revises: 
Create Date: 2026-03-21 13:06:33.275058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbf4eaa6b09b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('workshops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('language_codes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('services', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('driver_phone', sa.String(), nullable=False),
    sa.Column('driver_language', sa.String(length=5), nullable=True),
    sa.Column('driver_name', sa.String(), nullable=True),
    sa.Column('plate_number', sa.String(), nullable=True),
    sa.Column('truck_company', sa.String(), nullable=True),
    sa.Column('issue_type', sa.String(), nullable=True),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('location_text', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('assigned_workshop_id', sa.UUID(), nullable=True),
    sa.Column('eta_minutes', sa.Integer(), nullable=True),
    sa.Column('escalation_required', sa.Boolean(), nullable=False),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('abrupt_end', sa.Boolean(), nullable=False),
    sa.Column('driver_disconnected_mid_contact', sa.Boolean(), nullable=False),
    sa.Column('claimed_by_operator_id', sa.UUID(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_workshop_id'], ['workshops.id'], ),
    sa.ForeignKeyConstraint(['claimed_by_operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('call_type', sa.String(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('twilio_call_sid', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('structured_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_logs')
    op.drop_table('incidents')
    op.drop_table('workshops')
    op.drop_table('operators')
    # ### end Alembic commands ###
