import type { DailySignals } from "@/lib/domain/types";

export const scenarioInputs: Record<string, DailySignals> = {
  strategic: {
    date: "2026-03-21",
    timezone: "Europe/Paris",
    chronotype: "morning",
    objective: "performance",
    recoveryScore: 84,
    sleepHours: 7.8,
    sleepEfficiency: 89,
    sleepQuality: 83,
    strainYesterday: 10.2,
    hrvTrend: 0.28,
    restingHrDelta: -1,
    stressLoad: 31,
    socialBattery: 72,
    mentalFreshness: 86,
    meetingsPlanned: 3,
    focusBlocksPlanned: 2,
    decisionLoad: 56,
    travelLoad: 20,
    trainingIntent: "moderate",
  },
  focused: {
    date: "2026-03-21",
    timezone: "Europe/Paris",
    chronotype: "balanced",
    objective: "consistency",
    recoveryScore: 70,
    sleepHours: 7.1,
    sleepEfficiency: 84,
    sleepQuality: 73,
    strainYesterday: 11.8,
    hrvTrend: 0.08,
    restingHrDelta: 1,
    stressLoad: 43,
    socialBattery: 66,
    mentalFreshness: 71,
    meetingsPlanned: 4,
    focusBlocksPlanned: 2,
    decisionLoad: 59,
    travelLoad: 25,
    trainingIntent: "light",
  },
  lowReserve: {
    date: "2026-03-21",
    timezone: "Europe/Paris",
    chronotype: "balanced",
    objective: "balance",
    recoveryScore: 42,
    sleepHours: 5.9,
    sleepEfficiency: 71,
    sleepQuality: 49,
    strainYesterday: 15.7,
    hrvTrend: -0.24,
    restingHrDelta: 7,
    stressLoad: 71,
    socialBattery: 43,
    mentalFreshness: 47,
    meetingsPlanned: 5,
    focusBlocksPlanned: 1,
    decisionLoad: 72,
    travelLoad: 48,
    trainingIntent: "rest",
  },
  recoveryFirst: {
    date: "2026-03-21",
    timezone: "Europe/Paris",
    chronotype: "evening",
    objective: "recovery",
    recoveryScore: 30,
    sleepHours: 5.2,
    sleepEfficiency: 66,
    sleepQuality: 37,
    strainYesterday: 18.4,
    hrvTrend: -0.42,
    restingHrDelta: 10,
    stressLoad: 82,
    socialBattery: 35,
    mentalFreshness: 38,
    meetingsPlanned: 4,
    focusBlocksPlanned: 1,
    decisionLoad: 78,
    travelLoad: 55,
    trainingIntent: "rest",
  },
};
